

  CREATE TABLE CI_SA_TYPE_L 
   (	"CIS_DIVISION" CHAR(5) NOT NULL, 
	"SA_TYPE_CD" CHAR(8) NOT NULL, 
	"LANGUAGE_CD" CHAR(3) NOT NULL, 
	"DESCR" VARCHAR2(60) DEFAULT ' ' NOT NULL, 
	"DFLT_DESCR_ON_BILL" VARCHAR2(80) DEFAULT ' ' NOT NULL, 
	"ALERT_TEXT" VARCHAR2(50) DEFAULT ' ' NOT NULL, 
	"RCR_CHG_AMT_LABEL" VARCHAR2(60) DEFAULT ' ' NOT NULL, 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL, 
	"TOT_AMT_TOBILL_LBL" VARCHAR2(60) DEFAULT ' ' NOT NULL
   );

  
  ALTER TABLE CI_SA_TYPE_L ADD PRIMARY KEY ("CIS_DIVISION", "SA_TYPE_CD", "LANGUAGE_CD");

