CREATE TABLE CI_ACCT_PER 
   (	ACCT_ID CHAR(10) NOT NULL, 
	ACCT_REL_TYPE_CD CHAR(8) DEFAULT ' ' NOT NULL, 
	BILL_ADDR_SRCE_FLG CHAR(4) DEFAULT ' ' NOT NULL, 
	PER_ID CHAR(10) NOT NULL, 
	MAIN_CUST_SW CHAR(1) DEFAULT ' ' NOT NULL, 
	FIN_RESP_SW CHAR(1) DEFAULT ' ' NOT NULL, 
	THRD_PTY_SW CHAR(1) DEFAULT ' ' NOT NULL, 
	RECEIVE_COPY_SW CHAR(1) DEFAULT ' ' NOT NULL, 
	BILL_RTE_TYPE_CD CHAR(8) DEFAULT ' ' NOT NULL, 
	BILL_FORMAT_FLG CHAR(2) DEFAULT ' ' NOT NULL, 
	NBR_BILL_COPIES NUMBER(1,0) DEFAULT 0 NOT NULL, 
	VERSION NUMBER(5,0) DEFAULT 1 NOT NULL, 
	CUST_PO_ID VARCHAR2(20) DEFAULT ' ' NOT NULL, 
	NOTIFY_SW CHAR(1) DEFAULT ' ' NOT NULL, 
	NAME_PFX_SFX VARCHAR2(50) DEFAULT ' ' NOT NULL, 
	FX_SFX_FLG CHAR(2) DEFAULT ' ' NOT NULL, 
	QTE_RTE_TYPE_CD CHAR(12) DEFAULT ' ' NOT NULL, 
	RECV_QTE_SW CHAR(1) DEFAULT 'N' NOT NULL, 
    WEB_ACCESS_FLG CHAR(4) DEFAULT 'ALWD' NOT NULL
   )  ;


ALTER TABLE "CI_ACCT_PER" ADD PRIMARY KEY ("ACCT_ID", "PER_ID");