

  CREATE TABLE "CM_BILL_DUE_DT" 
   (	"BANK_ENTRY_EVENT_ID" VARCHAR2(60) NOT NULL, 
	"BILL_ID" CHAR(12) NOT NULL, 
	"DUE_DT" DATE, 
	"IS_MERCH_BALANCED" CHAR(1) DEFAULT 'N', 
	"UPLOAD_DTTM" DATE NOT NULL, 
	"STATUS_UPD_DTTM" DATE, 
	"PAY_DT" DATE NOT NULL, 
	"LINE_ID" CHAR(12) NOT NULL, 
	"BANKING_ENTRY_STATUS" VARCHAR2(15) NOT NULL
   ) ;

  ALTER TABLE CM_BILL_DUE_DT ADD CONSTRAINT CM_DUE_DT PRIMARY KEY ("BANK_ENTRY_EVENT_ID", "BILL_ID", "LINE_ID", "UPLOAD_DTTM");
 
