

  CREATE TABLE CM_CHARGE_TYPE_MAP 
   (	"CHARGE_TYPE_DESCR" VARCHAR2(100), 
	"AUTH_EVENT" VARCHAR2(10), 
	"PAYMENT_SCHEME" VARCHAR2(20), 
	"INTERNAL_AUTH_RESPONSE" VARCHAR2(20), 
	"CHILD_CHARGE_TYPE" VARCHAR2(20), 
	"PARENT_CHARGE_TYPE" VARCHAR2(20), 
	"AUTH_TRANSACTION_TYPE" VARCHAR2(20), 
	"TTYPE" VARCHAR2(20), 
	"CTYPE" VARCHAR2(20), 
	"JTYPE" VARCHAR2(20), 
	"PTYPE" VARCHAR2(20)
   );
