

  CREATE TABLE  "CM_MERCH_LEDGER_ACCT" 
   (	"PER_ID_NBR" VARCHAR2(90) NOT NULL, 
	"CIS_DIVISION" CHAR(5) NOT NULL, 
	"CURRENCY_CD" CHAR(3) NOT NULL, 
	"ACCT_NBR" VARCHAR2(30) NOT NULL, 
	"ACCTBAL" NUMBER, 
	"SA_TYPE_CD" CHAR(8) NOT NULL, 
	"SA_BAL" NUMBER NOT NULL, 
	"UPLOAD_DTTM" DATE NOT NULL, 
	"EXTRACT_FLG" CHAR(4) NOT NULL, 
	"EXTRACT_DTTM" DATE, 
	"ILM_DT" DATE, 
	"ILM_ARCH_SW" CHAR(1) DEFAULT 'N', 
	"TYPE" VARCHAR2(16)
   ) ;


  
    ALTER TABLE  CM_MERCH_LEDGER_ACCT ADD CONSTRAINT PK_LEDGER_ACCOUNT PRIMARY KEY ("PER_ID_NBR", "CIS_DIVISION", "CURRENCY_CD", "SA_TYPE_CD", "UPLOAD_DTTM");
