
  CREATE TABLE "CI_BILL_CHAR" 
   (	"BILL_ID" CHAR(12) NOT NULL,  
	"CHAR_TYPE_CD" CHAR(8) NOT NULL, 
	"SEQ_NUM" NUMBER(3,0) NOT NULL, 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL, 
	"CHAR_VAL" CHAR(16) DEFAULT ' 'NOT NULL, 
	"ADHOC_CHAR_VAL" VARCHAR2(254) DEFAULT ' ' NOT NULL , 
	"CHAR_VAL_FK1" VARCHAR2(50) DEFAULT ' ' NOT NULL, 
	"CHAR_VAL_FK2" VARCHAR2(50) DEFAULT ' ' NOT NULL, 
	"CHAR_VAL_FK3" VARCHAR2(50) DEFAULT ' ' NOT NULL, 
	"CHAR_VAL_FK4" VARCHAR2(50) DEFAULT ' ' NOT NULL, 
	"CHAR_VAL_FK5" VARCHAR2(50) DEFAULT ' ' NOT NULL, 
	"SRCH_CHAR_VAL" VARCHAR2(50) DEFAULT ' ' NOT NULL
   ) ;


  ALTER TABLE "CI_BILL_CHAR" ADD PRIMARY KEY ("BILL_ID", "CHAR_TYPE_CD", "SEQ_NUM");
  
