
  CREATE TABLE  "CI_CIS_DIVISION" 
   (	"CIS_DIVISION" CHAR(5) NOT NULL, 
	"CALENDAR_CD" CHAR(8) DEFAULT ' ' NOT NULL, 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL, 
	"COMMENTS" VARCHAR2(254), 
	"BASE_CURRENCY_CD" CHAR(3), 
	"TIME_ZONE_CD" CHAR(10), 
	"BILL_RTE_TYPE_CD" CHAR(8), 
	"PREM_ID" CHAR(10), 
	"BUS_OBJ_CD" CHAR(30), 
	"BO_STATUS_CD" CHAR(12), 
	"BILL_FORMAT_FLG" CHAR(2), 
	"DIVISION_STATUS_FLG" CHAR(2), 
	"BO_DATA_AREA" CLOB, 
	"ACCR_CYC_CD" CHAR(4), 
	"ACCR_ELIG_SW" CHAR(1) DEFAULT 'N' NOT NULL
   ) ;


  ALTER TABLE  "CI_CIS_DIVISION" ADD PRIMARY KEY ("CIS_DIVISION");
  