
  CREATE TABLE  "CI_PARTY" 
   (	"PARTY_UID" CHAR(10) NOT NULL, 
	"PARTY_TYPE_FLG" CHAR(4), 
	"PARTY_ID" CHAR(10), 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL
   ) ;


  ALTER TABLE  CI_PARTY ADD PRIMARY KEY ("PARTY_UID");
