
  CREATE TABLE CI_PRICEITEM
   (	 PRICEITEM_CD  CHAR(30) NOT NULL  , 
	 PI_STATUS_FLG  CHAR(4 ), 
	 UOM_CD  CHAR(4 ), 
	 PRICE_ITEM_TYPE_FLG  CHAR(4 ), 
	 ASGN_GLOBAL_PL_SW  CHAR(1 ), 
	 BUNDLE_SW  CHAR(1 ), 
	 BUNDLE_TYPE_FLG  CHAR(4 ), 
	 BUS_OBJ_CD  CHAR(30 ), 
	 VERSION  NUMBER(5,0) DEFAULT 1 NOT NULL  , 
	 BO_DATA_AREA  CLOB, 
	 SA_TYPE_CD  CHAR(8 ), 
	 ACCESS_GRP_CD  CHAR(12 ), 
	 IGNORE_SW  CHAR(1 ) DEFAULT 'N' NOT NULL  , 
	 PRICEITEM_TYPE  CHAR(30 ), 
	 BEST_OF_FLG  CHAR(8 ), 
	 PRICEITEM_AVAIL_FOR  CHAR(4 ), 
	 PRIMARY KEY ( PRICEITEM_CD )
  
   );
