 CREATE TABLE CI_PER_PER 
   (	"PER_ID1" CHAR(10 BYTE) NOT NULL, 
	"PER_ID2" CHAR(10 BYTE) NOT NULL, 
	"PER_REL_TYPE_CD" CHAR(8 BYTE) NOT NULL, 
	"START_DT" DATE NOT NULL, 
	"END_DT" DATE, 
	"VERSION" NUMBER(5,0) DEFAULT 1, 
	"FINAN_REL_SW" CHAR(1 BYTE) DEFAULT 'N'
   ); 
  ALTER TABLE CI_PER_PER ADD PRIMARY KEY ("PER_ID1", "PER_ID2", "PER_REL_TYPE_CD", "START_DT"); 