 
	 CREATE TABLE  "CI_CHAR_VAL_L" 
   (	"CHAR_TYPE_CD" CHAR(8 BYTE) NOT NULL  , 
	"CHAR_VAL" CHAR(16 BYTE) NOT NULL  , 
	"LANGUAGE_CD" CHAR(3 BYTE) NOT NULL  , 
	"DESCR" VARCHAR2(60 BYTE) DEFAULT ' ' NOT NULL  , 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL  , 
	"OWNER_FLG" CHAR(4 BYTE) DEFAULT ' ' NOT NULL  , 
	 PRIMARY KEY ("CHAR_TYPE_CD", "CHAR_VAL", "LANGUAGE_CD"));
	 