CREATE TABLE  CI_PER_ID 
   (	PER_ID CHAR(10) NOT NULL, 
	ID_TYPE_CD CHAR(8) NOT NULL, 
	PER_ID_NBR VARCHAR2(90) DEFAULT ' ', 
	PRIM_SW CHAR(1) DEFAULT ' ', 
	VERSION NUMBER(5,0) DEFAULT 1
   );
   
     ALTER TABLE CI_PER_ID ADD PRIMARY KEY ("PER_ID", "ID_TYPE_CD");