
  
  CREATE TABLE CI_PRICEASGN 
   (	"PRICE_ASGN_ID" CHAR(10) NOT NULL, 
	"OWNER_ID" CHAR(10), 
	"PA_OWNER_TYPE_FLG" CHAR(4) NOT NULL, 
	"START_DT"  DATE, 
	"END_DT"  DATE, 
	"PRICEITEM_CD" CHAR(30), 
	"TOU_CD" CHAR(8) DEFAULT ' ' NOT NULL, 
	"PRICE_CURRENCY_CD" CHAR(3), 
	"PRICE_STATUS_FLAG" CHAR(4), 
	"RS_CD" CHAR(8), 
	"BUS_OBJ_CD" CHAR(30), 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL, 
	"BO_DATA_AREA" CLOB, 
	"PA_TYPE_FLAG" CHAR(4), 
	"PRINT_IF_ZERO_SW" CHAR(1), 
	"PA_USAGE_FLG" CHAR(2) DEFAULT ' ' NOT NULL, 
	"IGNORE_SW" CHAR(1) DEFAULT 'N' NOT NULL, 
	"DO_NOT_AGG_SW" CHAR(1) DEFAULT 'Y' NOT NULL, 
	"SCHEDULE_CD" CHAR(12), 
	"TXN_RATING_CRITERIA" CHAR(4) DEFAULT 'DNRT', 
	"ADV_PRC_SW" CHAR(1) DEFAULT 'N', 
	"ELIGIBILITY_SW" CHAR(1) DEFAULT 'N'
   ) ;

  ALTER TABLE CI_PRICEASGN ADD PRIMARY KEY ("PRICE_ASGN_ID");
