
  CREATE TABLE CI_PRICEASGN_PARM 
   (	"PRICE_ASGN_ID" CHAR(10) NOT NULL, 
	"PRICE_PARM_CD" VARCHAR2(30) NOT NULL, 
	"PRICE_PARM_VAL" VARCHAR2(254) NOT NULL, 
	"OVERRIDE_PRIORITY_NUM" NUMBER(3,0) , 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL
   );
ALTER TABLE CI_PRICEASGN_PARM ADD PRIMARY KEY ("PRICE_ASGN_ID","PRICE_PARM_CD");
