

  CREATE TABLE CI_RC_CHAR 
   (	"RS_CD" CHAR(8) NOT NULL, 
	"EFFDT" DATE NOT NULL, 
	"RC_SEQ" NUMBER(3,0) NOT NULL, 
	"CHAR_TYPE_CD" CHAR(8) NOT NULL, 
	"CHAR_VAL" CHAR(16) DEFAULT ' ' NOT NULL, 
	"ADHOC_CHAR_VAL" VARCHAR2(254) DEFAULT ' ' NOT NULL, 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL
   );

  ALTER TABLE CI_RC_CHAR ADD PRIMARY KEY ("RS_CD", "EFFDT", "RC_SEQ", "CHAR_TYPE_CD");

  
